### ISSUE TITLE
Duplicates in TOSCA sections

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/iac-blueprint-builder#10]
### Current behaviour
Multiple invocations of `/parse` method with same JSON produce a TOSCA service template that contains duplicates of TOSCA definitions. 
For instance we have a model that contains **inputs**
```
  "https://www.sodalite.eu/ontologies/workspace/1/fj2uu6snlcq3ca5bdipdfjnobc/topology_template_inputs": {
    "inputs": [
      {
        "https://www.sodalite.eu/ontologies/workspace/1/u1lnsc0k73f78hmqhe2b7jfac3/username": {
          "specification": {
            "type": "string"
          }
        }
      },
      {
        "https://www.sodalite.eu/ontologies/workspace/1/fppvcga90lvljdklahb57ghpt6/docker-host-ip": {
          "specification": {
            "type": "string"
          }
        }
      }
    ]
  }
```

then after 3 invocations the output would be
```
topology_template:

  inputs:  
    username:  
      type: string 
    docker-host-ip:  
      type: string 
  inputs:  
    username:  
      type: string 
    docker-host-ip:  
      type: string 
  inputs:  
    username:  
      type: string 
    docker-host-ip:  
      type: string 
```
### Expected behaviour
Number of occurrences in the output produced matches the JSON model.
E.g in the case above it would be
```
topology_template:

  inputs:  
    username:  
      type: string 
    docker-host-ip:  
      type: string 
```
