### ISSUE TITLE
tosca.interfaces.node.lifecycle.Standard interface implementation is limited

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/iac-blueprint-builder#12]
tosca.interfaces.node.lifecycle.Standard interface implementation is limited only to `create` and `delete` operations

### Current behaviour 
With JSON input like this
```
"https://www.sodalite.eu/ontologies/workspace/1/89c9fua869bu2hilu8roikeeo8/sodalite.nodes.hpc.job.torque": {
    "type": "https://www.sodalite.eu/ontologies/tosca/tosca.nodes.SoftwareComponent",
    "isNodeTemplate": false,
    "interfaces": [
      {
        "https://www.sodalite.eu/ontologies/tosca/Standard": {
          "specification": {
            "type": {
              "https://www.sodalite.eu/ontologies/tosca/tosca.interfaces.node.lifecycle.Standard": {
                "label": "tosca.interfaces.node.lifecycle.Standard"
              }
            },
            "operations": {
              "start": {
                "implementation": {
                  "primary": {
                    "url": "some_url",
                    "path": "some_path"
                  }
                }
              },
              "configure": {
                "implementation": {
                  "primary": {
                    "url": "some_url",
                    "path": "some_path"
                  }
                }
              }
            }
          }
        }
      }
    ]
  },
```
TOSCA output would be this

```
  sodalite.nodes.hpc.job.torque:  
    derived_from: tosca.nodes.SoftwareComponent 
    interfaces:  
      Standard: 
        type: tosca.interfaces.node.lifecycle.Standard 
        operations: 
```
### Expected behaviour 

TOSCA output should be

```
  sodalite.nodes.hpc.job.torque:  
    derived_from: tosca.nodes.SoftwareComponent 
     interfaces:  
      Standard: 
        type: tosca.interfaces.node.lifecycle.Standard 
        operations: 
          configure: 
            implementation: 
              primary: some_path
          start: 
            implementation: 
              primary: some_path

```
