### ISSUE TITLE
Relationship types are placed in node_type section

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/iac-blueprint-builder#16]
### Current behaviour
When parsing an AADM JSON with relationship types defined, they are placed in node_types section 
E.g with AADM like this
```
{
    "name" : "hpc_clinical.aadm",
    "data" : {
      "https://www.sodalite.eu/ontologies/workspace/1/8h0t0m2p2c22gje5fd5n6f5end/AADM_jds55bipkbhfj195h0lb1s28tt": {
        "type": "AbstractApplicationDeploymentModel",
        "createdBy": "https://www.sodalite.eu/ontologies/workspace/1/8h0t0m2p2c22gje5fd5n6f5end/27827d44-0f6c-11ea-8d71-362b9e155667",
        "createdAt": "2020-09-17T13:09:14.367+03:00",
        "version": "1",
        "https://www.sodalite.eu/ontologies/workspace/1/89c9fua869bu2hilu8roikeeo8/sodalite.relationships.jobHostedOn": {
            "type": "https://www.sodalite.eu/ontologies/tosca/tosca.relationships.HostedOn",
            "isNodeTemplate": false            }
      }
        
    }
}
```
we get
```
tosca_definitions_version: tosca_simple_yaml_1_3  

node_types: 

  sodalite.relationships.jobHostedOn:  
    derived_from: tosca.relationships.HostedOn 
```

### Expected behaviour
Relationship types are placed in relationship_types section 
```
tosca_definitions_version: tosca_simple_yaml_1_3  

relationship_types: 

  sodalite.relationships.jobHostedOn:  
    derived_from: tosca.relationships.HostedOn 
```
