### ISSUE TITLE
TOSCA is generated with empty operations clause

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/iac-blueprint-builder#9]
### Current behaviour
When input JSON for **node_type** contains **interfaces** without any operations defined, e.g.
```
    "interfaces": [
      {
        "https://www.sodalite.eu/ontologies/tosca/Standard": {
          "specification": {
            "type": {
              "https://www.sodalite.eu/ontologies/tosca/tosca.interfaces.node.lifecycle.Standard": {
                "label": "tosca.interfaces.node.lifecycle.Standard"
              }
            }
          }
        }
      }
    ]
```
the output TOSCA contains empty **operations** clause
```
    interfaces:  
      Standard: 
        type: tosca.interfaces.node.lifecycle.Standard 
        operations: 
```
### Expected behaviour

Output TOSCA should contain only interface type
```
    interfaces:  
      Standard: 
        type: tosca.interfaces.node.lifecycle.Standard 
```
